### ISSUE TITLE
bowtie-1.2.1.1 randomly reports wrong lines of output when processing reads from stdin

### ISSUE THREAD

**Issue by ankebusch** [BenLangmead/bowtie#69]
I've used bowtie 1.2.1.1 with input from stdin and with the following parameters: 
`zcat DATAFILE.fastq.gz | bowtie -q --sam --phred33-quals --tryhard --best --strata --chunkmbs 256 -p 8 -v 1 -M 1 PATHTOINDEX/GRCm38.p4 -`
The call reported in the resulting sam file is the following:
`bowtie-align --wrapper basic-0 -q --sam --phred33-quals --tryhard --best --strata --chunkmbs 256 -p 8 -v 1 -M 1 PATHTOINDEX/GRCm38.p4 -`
Unfortunately, this command produced random erroneous output, which is not reproducible since it happens randomly. An example of a wrong output line would be:
`NB501946:83:HLJCMBGX3:1:11101:24657:11782	16	NB501946:	3:HLJCMBGX3:	:11101:23739:11977	0	EEEEEA	XA:i:	TAAGTGCGTGCATGTATATGA	AEEEEEEEEEEEEEEEEEEEE	XA:i:1	MD:Z:20T0	NM:i:1	XM:i:2`
After re-running the same command, the line is output correctly as:
`NB501946:83:HLJCMBGX3:1:11101:24657:11782	16	chr1	49321593	0	18M	*	0	0	TGGGGGCTCGTCCGGGAT	EAEEEEEEEEEEEEEEEA	XA:i:0	MD:Z:18	NM:i:0	XM:i:2`
All of this was run in a HPC environment running slurm and integrated in a pipeline based on bpipe.
Do you have any idea what could be the problem? Running the same commands with bowtie 1.1.2, everything ran smoothly and without any errors.

**Comment by ndaniel** [comment]
This might be similar to https://github.com/BenLangmead/bowtie/issues/54

**Comment by ch4rr0** [comment]
Unfortunately this is one of the issues I have had near 0 luck reproducing, but now that it has come up again I will resume investigating. If it's not too much to ask can you try reproducing the issue with a beta build for an upcoming release? It would be nice to know whether this is still an issue before finalizing the release. I will provide the binary if you're willing to participate.

**Comment by ankebusch** [comment]
Sure, I'd be happy to test the beta build.

**Comment by ch4rr0** [comment]
Here's the beta package. Please let me know if the issue is still present in the packaged binaries.
[bowtie-1.2.2-beta-linux-x86_64.zip](https://github.com/BenLangmead/bowtie/files/1488459/bowtie-1.2.2-beta-linux-x86_64.zip)

**Comment by ankebusch** [comment]
Unfortunately, the zipped package is empty. After unzipping, it's just an empty folder. Could you double-check it's the correct file?

**Comment by ch4rr0** [comment]
Sorry about that. Here's a link to the pre-release: https://github.com/BenLangmead/bowtie/releases/tag/v1.2.2-beta

**Comment by tbooth** [comment]
Hi,
Came here as I seem to be seeing a very similar problem while running fastq_screen, which is a Perl script that calls bowtie vs. a selection of genomes then parses the SAM lines from STDOUT.
I'm also on an HPC cluster and am only seeing this quite rarely (like one line in a million lines of output, making about half my fastq_screen runs fail) and only ever when running under SLURM.
The input in my case was **not** coming from STDIN but from a file. The problem seems to vanish with ```-p 1``` suggesting something non-thread-safe is happening while printing each line of output.

The good news is that I've just tried 1.2.2-beta and everything has worked, so it looks like my problem is fixed, and hopefully the issue is also fixed for the original reporter. If not, I'll subscribe to alerts on this bug and try to help pinning the problem down if I can - I know from my own debugging experience how much of a pain these things can be!

Cheers,
TIM

**Comment by ankebusch** [comment]
I've been running many tests with lots of repetitions using version 1.2.2-beta during the last two days since like I said before the error is not reproducible and happening randomly. Unfortunately for me the error persists also with the latest beta version. But also for me, the problem vanishes when running bowtie using just one thread (-p 1). If I increase the allocated memory (under SLURM), the frequency of the error seems to decrease, but so far I was not able to find a multi-threading setting, which did not produce the error at some point.

One more thing I wanted to mention: bowtie itself does not realize this problem. The summary output is just fine reporting the mapping statistics. Only by parsing the sam file afterwards I was able to spot the error. And actually it was also by running fastq_screen when I first became aware of the problem.

Do you have any suggestion what other settings/changes I could test?

**Comment by tbooth** [comment]
Hi,
I'm now seeing errors with the beta, so I think my optimism was misplaced. How annoying. Maybe the errors are just less frequent.
I have a small patch to fastqscreen that makes the errors fatal and at least gives me a clean failure - I've sent it to the author of fastqscreen but if you want it just let me know.
Happy to test any code you want to send my way.
For now I'm going back to (-p 1) and taking the performance hit.
Cheers,
TIM

**Comment by BenLangmead** [comment]
@ch4rr0 and I have been looking at this very carefully and haven't had any success so far.  One thing I would suggest trying is to run with `-p X --reorder` for some X>1 and let us know if you still see the problem then.  Other things we're curious about:

1. What length reads are you aligning?
2. What value of `-p` are you using? (@ankebusch -- you already told us you were using `-p 8` -- thanks)
3. What sort of file system are you writing to?  (local disk?  shared storage?)

**Comment by ankebusch** [comment]
Hi again :)

Let me first answer your questions:

1) my reads are mainly miRNAs, i.e. around 22bp
2) still `-p 8`
3) I'm using an HPC cluster running SLURM and I'm using shared storage

I've re-run my tests several times. 

A) First of all, I switch from reading from stdin to directly providing the fastq.gz file to bowtie and the error persists. 
B) Then I re-ran everything using `-p 8 --reorder` as you suggested. This setting results in bowtie either just getting "Killed" (no further note) or in one of the following error messages:
```
*** Error in `bowtie-align': double free or corruption (out): 0x00007fae38008760 ***
*** Error in `bowtie-align': corrupted double-linked list: 0x00007f3700076380 ***
*** Error in `bowtie-align': double free or corruption (!prev): 0x00007f7a4800b280 ***
*** Error in `bowtie-align': free(): invalid next size (normal): 0x00007f1168007d70 ***
```
I tried to increase the reserved memory, but it didn't help. Even when reserving 64GB of RAM is crashes.

**Comment by ch4rr0** [comment]
I am building a new binary that  should fix these issues. I will have it uploaded shortly.

**Comment by ch4rr0** [comment]
I updated the [binary.](https://github.com/BenLangmead/bowtie/releases/download/v1.2.2-beta/bowtie-1.2.2-beta-linux-x86_64.zip)

**Comment by BenLangmead** [comment]
Has anyone had a chance to give this new binary (posted by @ch4rr0 2 days ago) a try?  It certainly solved a similar problem that we were able to reproduce on our end. @tbooth @ankebusch

**Comment by ankebusch** [comment]
Yes, I ran many repeated tests over the last two days. Since the error happens randomly, it's never been reproducible. During my tests with the first 1.2.2-beta the error occured at the latest after 100 re-runs of the same bowtie call. Now, with the new 1.2.2-beta you sent two days ago, I've run approximately 250 repetitions of the same bowtie call and did not see the error again (without using `--reorder`). 

However, when using `--reorder` I noticed that it requires huge amounts of memory. My fastq file has approximately 7.5 million smallRNA reads. When running bowtie on 8 cores and reserving 15GB per core, the job got killed. Thus, 120GB total were not enough. Then I rerun it on 8 cores with 20GB per core and finally, it finished without crashing. Thus, the memory used by bowtie is surprisingly high. Not sure, if this could be a problem of the queueing system?

**Comment by tbooth** [comment]
Hi,
Pleased to report that the new binary has fixed the problem for me. Running with 2 threads about half my fastq_screen runs were failing before. Now after switching binaries the last batch have all worked.
Many thanks for fixing this and for continuing to support bowtie!
Cheers,
TIM
